# coding: utf-8

"""
    ocrapi

    The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_ocr_api_client
from cloudmersive_ocr_api_client.api.receipts_api import ReceiptsApi  # noqa: E501
from cloudmersive_ocr_api_client.rest import ApiException


class TestReceiptsApi(unittest.TestCase):
    """ReceiptsApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_ocr_api_client.api.receipts_api.ReceiptsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_receipts_photo_to_csv(self):
        """Test case for receipts_photo_to_csv

        Convert a photo of a receipt into a CSV file containing structured information from the receipt  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
