# coding: utf-8

"""
    ocrapi

    The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_ocr_api_client
from cloudmersive_ocr_api_client.models.receipt_line_item import ReceiptLineItem  # noqa: E501
from cloudmersive_ocr_api_client.rest import ApiException


class TestReceiptLineItem(unittest.TestCase):
    """ReceiptLineItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReceiptLineItem(self):
        """Test ReceiptLineItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_ocr_api_client.models.receipt_line_item.ReceiptLineItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
