# coding: utf-8

"""
    ocrapi

    The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FormTableColumnDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'column_id': 'str',
        'top_anchor': 'str',
        'anchor_mode': 'str',
        'data_type': 'str',
        'minimum_character_count': 'int',
        'allow_numeric_digits': 'bool'
    }

    attribute_map = {
        'column_id': 'ColumnID',
        'top_anchor': 'TopAnchor',
        'anchor_mode': 'AnchorMode',
        'data_type': 'DataType',
        'minimum_character_count': 'MinimumCharacterCount',
        'allow_numeric_digits': 'AllowNumericDigits'
    }

    def __init__(self, column_id=None, top_anchor=None, anchor_mode=None, data_type=None, minimum_character_count=None, allow_numeric_digits=None):  # noqa: E501
        """FormTableColumnDefinition - a model defined in Swagger"""  # noqa: E501

        self._column_id = None
        self._top_anchor = None
        self._anchor_mode = None
        self._data_type = None
        self._minimum_character_count = None
        self._allow_numeric_digits = None
        self.discriminator = None

        if column_id is not None:
            self.column_id = column_id
        if top_anchor is not None:
            self.top_anchor = top_anchor
        if anchor_mode is not None:
            self.anchor_mode = anchor_mode
        if data_type is not None:
            self.data_type = data_type
        if minimum_character_count is not None:
            self.minimum_character_count = minimum_character_count
        if allow_numeric_digits is not None:
            self.allow_numeric_digits = allow_numeric_digits

    @property
    def column_id(self):
        """Gets the column_id of this FormTableColumnDefinition.  # noqa: E501

        The identifier of the field; use this to identify which field is being referenced  # noqa: E501

        :return: The column_id of this FormTableColumnDefinition.  # noqa: E501
        :rtype: str
        """
        return self._column_id

    @column_id.setter
    def column_id(self, column_id):
        """Sets the column_id of this FormTableColumnDefinition.

        The identifier of the field; use this to identify which field is being referenced  # noqa: E501

        :param column_id: The column_id of this FormTableColumnDefinition.  # noqa: E501
        :type: str
        """

        self._column_id = column_id

    @property
    def top_anchor(self):
        """Gets the top_anchor of this FormTableColumnDefinition.  # noqa: E501

        Optional - the top anchor of the column heading  # noqa: E501

        :return: The top_anchor of this FormTableColumnDefinition.  # noqa: E501
        :rtype: str
        """
        return self._top_anchor

    @top_anchor.setter
    def top_anchor(self, top_anchor):
        """Sets the top_anchor of this FormTableColumnDefinition.

        Optional - the top anchor of the column heading  # noqa: E501

        :param top_anchor: The top_anchor of this FormTableColumnDefinition.  # noqa: E501
        :type: str
        """

        self._top_anchor = top_anchor

    @property
    def anchor_mode(self):
        """Gets the anchor_mode of this FormTableColumnDefinition.  # noqa: E501

        Optional - the matching mode for the anchor.  Possible values are Complete (requires the entire anchor to match) and Partial (allows only part of the anchor to match).  Default is Partial.  # noqa: E501

        :return: The anchor_mode of this FormTableColumnDefinition.  # noqa: E501
        :rtype: str
        """
        return self._anchor_mode

    @anchor_mode.setter
    def anchor_mode(self, anchor_mode):
        """Sets the anchor_mode of this FormTableColumnDefinition.

        Optional - the matching mode for the anchor.  Possible values are Complete (requires the entire anchor to match) and Partial (allows only part of the anchor to match).  Default is Partial.  # noqa: E501

        :param anchor_mode: The anchor_mode of this FormTableColumnDefinition.  # noqa: E501
        :type: str
        """

        self._anchor_mode = anchor_mode

    @property
    def data_type(self):
        """Gets the data_type of this FormTableColumnDefinition.  # noqa: E501

        The data type of the field; possible values are INTEGER (Integer value), STRING (Arbitrary string value, spaces are permitted), DATE (Date in a structured format), DECIMAL (Decimal number), ALPHANUMERIC (Continuous alphanumeric string with no spaces), STRINGNOWHITESPACE (A string that contains no whitespace characters), SERIALNUMBER (A serial-number style string that contains letters and numbers, and certain symbols; must contain at least one number), ALPHAONLY (Alphabet characters only, no numbers or symbols or whitespace)  # noqa: E501

        :return: The data_type of this FormTableColumnDefinition.  # noqa: E501
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this FormTableColumnDefinition.

        The data type of the field; possible values are INTEGER (Integer value), STRING (Arbitrary string value, spaces are permitted), DATE (Date in a structured format), DECIMAL (Decimal number), ALPHANUMERIC (Continuous alphanumeric string with no spaces), STRINGNOWHITESPACE (A string that contains no whitespace characters), SERIALNUMBER (A serial-number style string that contains letters and numbers, and certain symbols; must contain at least one number), ALPHAONLY (Alphabet characters only, no numbers or symbols or whitespace)  # noqa: E501

        :param data_type: The data_type of this FormTableColumnDefinition.  # noqa: E501
        :type: str
        """

        self._data_type = data_type

    @property
    def minimum_character_count(self):
        """Gets the minimum_character_count of this FormTableColumnDefinition.  # noqa: E501

        Optional - the target number of digits in the field; useful for fixed-length fields  # noqa: E501

        :return: The minimum_character_count of this FormTableColumnDefinition.  # noqa: E501
        :rtype: int
        """
        return self._minimum_character_count

    @minimum_character_count.setter
    def minimum_character_count(self, minimum_character_count):
        """Sets the minimum_character_count of this FormTableColumnDefinition.

        Optional - the target number of digits in the field; useful for fixed-length fields  # noqa: E501

        :param minimum_character_count: The minimum_character_count of this FormTableColumnDefinition.  # noqa: E501
        :type: int
        """

        self._minimum_character_count = minimum_character_count

    @property
    def allow_numeric_digits(self):
        """Gets the allow_numeric_digits of this FormTableColumnDefinition.  # noqa: E501

        Optional - set to false to block values that contain numeric digits, set to true to allow numeric digits  # noqa: E501

        :return: The allow_numeric_digits of this FormTableColumnDefinition.  # noqa: E501
        :rtype: bool
        """
        return self._allow_numeric_digits

    @allow_numeric_digits.setter
    def allow_numeric_digits(self, allow_numeric_digits):
        """Sets the allow_numeric_digits of this FormTableColumnDefinition.

        Optional - set to false to block values that contain numeric digits, set to true to allow numeric digits  # noqa: E501

        :param allow_numeric_digits: The allow_numeric_digits of this FormTableColumnDefinition.  # noqa: E501
        :type: bool
        """

        self._allow_numeric_digits = allow_numeric_digits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FormTableColumnDefinition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FormTableColumnDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
