# coding: utf-8

"""
    ocrapi

    The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OcrWordElement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'word_text': 'str',
        'line_number': 'int',
        'word_number': 'int',
        'x_left': 'int',
        'y_top': 'int',
        'width': 'int',
        'height': 'int',
        'confidence_level': 'float',
        'block_number': 'int',
        'paragraph_number': 'int',
        'page_number': 'int'
    }

    attribute_map = {
        'word_text': 'WordText',
        'line_number': 'LineNumber',
        'word_number': 'WordNumber',
        'x_left': 'XLeft',
        'y_top': 'YTop',
        'width': 'Width',
        'height': 'Height',
        'confidence_level': 'ConfidenceLevel',
        'block_number': 'BlockNumber',
        'paragraph_number': 'ParagraphNumber',
        'page_number': 'PageNumber'
    }

    def __init__(self, word_text=None, line_number=None, word_number=None, x_left=None, y_top=None, width=None, height=None, confidence_level=None, block_number=None, paragraph_number=None, page_number=None):  # noqa: E501
        """OcrWordElement - a model defined in Swagger"""  # noqa: E501

        self._word_text = None
        self._line_number = None
        self._word_number = None
        self._x_left = None
        self._y_top = None
        self._width = None
        self._height = None
        self._confidence_level = None
        self._block_number = None
        self._paragraph_number = None
        self._page_number = None
        self.discriminator = None

        if word_text is not None:
            self.word_text = word_text
        if line_number is not None:
            self.line_number = line_number
        if word_number is not None:
            self.word_number = word_number
        if x_left is not None:
            self.x_left = x_left
        if y_top is not None:
            self.y_top = y_top
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if confidence_level is not None:
            self.confidence_level = confidence_level
        if block_number is not None:
            self.block_number = block_number
        if paragraph_number is not None:
            self.paragraph_number = paragraph_number
        if page_number is not None:
            self.page_number = page_number

    @property
    def word_text(self):
        """Gets the word_text of this OcrWordElement.  # noqa: E501

        Text of the word  # noqa: E501

        :return: The word_text of this OcrWordElement.  # noqa: E501
        :rtype: str
        """
        return self._word_text

    @word_text.setter
    def word_text(self, word_text):
        """Sets the word_text of this OcrWordElement.

        Text of the word  # noqa: E501

        :param word_text: The word_text of this OcrWordElement.  # noqa: E501
        :type: str
        """

        self._word_text = word_text

    @property
    def line_number(self):
        """Gets the line_number of this OcrWordElement.  # noqa: E501

        Line number of the word  # noqa: E501

        :return: The line_number of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._line_number

    @line_number.setter
    def line_number(self, line_number):
        """Sets the line_number of this OcrWordElement.

        Line number of the word  # noqa: E501

        :param line_number: The line_number of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._line_number = line_number

    @property
    def word_number(self):
        """Gets the word_number of this OcrWordElement.  # noqa: E501

        Index of the word in the line  # noqa: E501

        :return: The word_number of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._word_number

    @word_number.setter
    def word_number(self, word_number):
        """Sets the word_number of this OcrWordElement.

        Index of the word in the line  # noqa: E501

        :param word_number: The word_number of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._word_number = word_number

    @property
    def x_left(self):
        """Gets the x_left of this OcrWordElement.  # noqa: E501

        X location of the left edge of the word in pixels  # noqa: E501

        :return: The x_left of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._x_left

    @x_left.setter
    def x_left(self, x_left):
        """Sets the x_left of this OcrWordElement.

        X location of the left edge of the word in pixels  # noqa: E501

        :param x_left: The x_left of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._x_left = x_left

    @property
    def y_top(self):
        """Gets the y_top of this OcrWordElement.  # noqa: E501

        Y location of the top edge of the word in pixels  # noqa: E501

        :return: The y_top of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._y_top

    @y_top.setter
    def y_top(self, y_top):
        """Sets the y_top of this OcrWordElement.

        Y location of the top edge of the word in pixels  # noqa: E501

        :param y_top: The y_top of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._y_top = y_top

    @property
    def width(self):
        """Gets the width of this OcrWordElement.  # noqa: E501

        Width of the word in pixels  # noqa: E501

        :return: The width of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this OcrWordElement.

        Width of the word in pixels  # noqa: E501

        :param width: The width of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this OcrWordElement.  # noqa: E501

        Height of the word in pixels  # noqa: E501

        :return: The height of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this OcrWordElement.

        Height of the word in pixels  # noqa: E501

        :param height: The height of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def confidence_level(self):
        """Gets the confidence_level of this OcrWordElement.  # noqa: E501

        Confidence level of the machine learning result; possible values are 0.0 (lowest accuracy) - 1.0 (highest accuracy)  # noqa: E501

        :return: The confidence_level of this OcrWordElement.  # noqa: E501
        :rtype: float
        """
        return self._confidence_level

    @confidence_level.setter
    def confidence_level(self, confidence_level):
        """Sets the confidence_level of this OcrWordElement.

        Confidence level of the machine learning result; possible values are 0.0 (lowest accuracy) - 1.0 (highest accuracy)  # noqa: E501

        :param confidence_level: The confidence_level of this OcrWordElement.  # noqa: E501
        :type: float
        """

        self._confidence_level = confidence_level

    @property
    def block_number(self):
        """Gets the block_number of this OcrWordElement.  # noqa: E501

        Index of the containing block  # noqa: E501

        :return: The block_number of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._block_number

    @block_number.setter
    def block_number(self, block_number):
        """Sets the block_number of this OcrWordElement.

        Index of the containing block  # noqa: E501

        :param block_number: The block_number of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._block_number = block_number

    @property
    def paragraph_number(self):
        """Gets the paragraph_number of this OcrWordElement.  # noqa: E501

        Index of the containing paragraph  # noqa: E501

        :return: The paragraph_number of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._paragraph_number

    @paragraph_number.setter
    def paragraph_number(self, paragraph_number):
        """Sets the paragraph_number of this OcrWordElement.

        Index of the containing paragraph  # noqa: E501

        :param paragraph_number: The paragraph_number of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._paragraph_number = paragraph_number

    @property
    def page_number(self):
        """Gets the page_number of this OcrWordElement.  # noqa: E501

        Index of the containing page  # noqa: E501

        :return: The page_number of this OcrWordElement.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this OcrWordElement.

        Index of the containing page  # noqa: E501

        :param page_number: The page_number of this OcrWordElement.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OcrWordElement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OcrWordElement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
